# Generated by Django 4.1.7 on 2023-05-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=100)),
                ('cleaner', models.CharField(max_length=100)),
                ('NO_OF_staff', models.IntegerField()),
            ],
        ),
    ]
